{{- range .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.name }}-{{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .size | default "1Gi" | quote }}
{{- end }}
